# Generated by Django 5.0.7 on 2024-07-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatId',
            field=models.TextField(default=''),
        ),
    ]
